### ISSUE TITLE
Please license the code

### ISSUE THREAD

**Issue by TheTincho** [beevik/ntp#1]
Hi,

I am packaging dependencies for prometheus.io for Debian, and since they use your package I need to package it too. The problem is that without an explicit license attached to the code it is not legal for Debian to include the package.

Could you add that?

**Comment by juliusv** [comment]
That package is a single file with 70 lines of code. So in case we don't get an answer soon and that is blocking official Prometheus debs, it should be easy enough to rewrite it by ourselves.

**Comment by beevik** [comment]
done!

**Comment by beevik** [comment]
License added. Closing issue.

**Comment by juliusv** [comment]
Thanks :)
