### ISSUE TITLE
KoD support?

### ISSUE THREAD

**Issue by mengzhuo** [beevik/ntp#12]
Any plan on KoD support?

> In NTPv4 and SNTPv4, packets of this kind are called Kiss-o'-Death (KoD) packets, and the ASCII messages they convey are called kiss codes. The KoD packets got their name because an early use was to tell clients to stop sending packets that violate server access controls.

**Comment by beevik** [comment]
I have no current plans, but feel free to submit a pull request if you'd like to add it.

**Comment by beevik** [comment]
Thought you might like to know that kiss of death is now handled in `Response.Validate` and `Time` calls.
