### ISSUE TITLE
Don't change stratum data

### ISSUE THREAD

**Issue by abh** [beevik/ntp#18]
It's confusing that stratum=0 gets changed to 16.

I understand that implementations are suggested to do this, but I think it's "later" than "when processing packets". For my application I want to know what the server said.

The RFC also says to process the referenceID separately if the stratum is 0, right now that's impossible to do correctly with the Go client because you can't know if the server said 16 or if it said 0 and it was changed.

**Comment by beevik** [comment]
PR https://github.com/beevik/ntp/pull/25 adds a `KissCode` field to the ntp response, so you can examine why you received a kiss of death.
