### ISSUE TITLE
time.Duration to NtpTime

### ISSUE THREAD

**Issue by traveltoaiur** [beevik/ntp#21]
Any chance for you to add the reverse function of (t ntpTimeShort) Duration() time.Duration?

like a toNtpTime(t time.Duration) NtpTime function?

I can't figure the formula myself.

Or can you provide any link where I can find the formula? Sorry but I can't contact you privately

**Comment by beevik** [comment]
This is probably what you'd want.  (This code rounds up the fractional component, which the `toNtpTime` version doesn't do, but probably should.)
```go
func toNtpTimeShort(d time.Duration) ntpTimeShort {
	nsec := uint64(d)
	sec := nsec / nanoPerSec
	frac := (((nsec - sec*nanoPerSec) << 16) + nanoPerSec - 1) / nanoPerSec
	return ntpTimeShort(uint32(sec<<16 | frac))
}
```

**Comment by traveltoaiur** [comment]
what about a **`toNtpTime`** one?

**Comment by beevik** [comment]
It would be almost the same as the `time.Time` version of `toNtpTime`, with the first line replaced:

```go
func toNtpTimeDuration(d time.Duration) ntpTime {
	nsec := uint64(d)
	sec := nsec / nanoPerSec
	frac := (((nsec - sec*nanoPerSec) << 32) + nanoPerSec - 1) / nanoPerSec
	return ntpTime(sec<<32 | frac)
}
```

**Comment by traveltoaiur** [comment]
The `toNtpTimeDuration` function works when I have a positive duration.
If i get the output of `toNtpTimeDuration` and convert it back into a duration via the `.Duration()` function I get the exact same duration that I used first.
But whenever I use a negative duration, and I output the result into your `.Duration()` function, I get a value completely different from my original negative duration.

Any idea on how to have a direct conversion?

**Comment by beevik** [comment]
The RFC5905 32-bit and 64-bit time formats are not capable of representing negative time durations.  They allow only unsigned seconds values.  See [this section](https://tools.ietf.org/html/rfc5905#section-6).

**Comment by traveltoaiur** [comment]
Indeed. And that's why you're converting to times before calculating the offset.

Thank you
