### ISSUE TITLE
Support IPv6-only hosts

### ISSUE THREAD

**Issue by bluecmd** [beevik/ntp#29]
Hi,

I have machines that have only IPv6 connectivity. Using `net.ResolveUDPAddr` with `udp` will [always](https://go-review.googlesource.com/c/go/+/47554/)* return IPv4 if the DNS name has an IPv4 configured, regardless if the system can route it.

Consider either giving the user a possibility of specifying "udp6" for IPv6, or better yet try with "udp" first, then "udp4" and then "udp6".

Thanks!
\* See https://golang.org/src/net/ipsock.go line 85.

**Comment by bluecmd** [comment]
This is how it looks like, FWIW:
```
1970/01/01 00:00:31 Failed to contact NTP server time1.google.com (skipping): dial udp 216.239.35.0:123: connect: network is unreachable
1970/01/01 00:00:31 Failed to contact NTP server time2.google.com (skipping): dial udp 216.239.35.4:123: connect: network is unreachable
1970/01/01 00:00:31 Failed to contact NTP server time3.google.com (skipping): dial udp 216.239.35.8:123: connect: network is unreachable
1970/01/01 00:00:31 Failed to contact NTP server time4.google.com (skipping): dial udp 216.239.35.12:123: connect: network is unreachable
```

**Comment by beevik** [comment]
Thanks for the suggestion.  I've made the protocol configurable in https://github.com/beevik/ntp/commit/53ffc1864695f04a9261eaaba263b1e85e5795f3.

**Comment by bluecmd** [comment]
Great! Thanks :+1:
