### ISSUE TITLE
Two test cases try to access the Internet

### ISSUE THREAD

**Issue by bdrung** [beevik/ntp#37]
Running the test cases during package build on Ubuntu fail [1]:

```
   dh_auto_test -O--builddirectory=_build -O--buildsystem=golang
	cd _build && go test -vet=off -v -p 4 github.com/beevik/ntp
=== RUN   TestTime
    ntp_test.go:34: [0.beevik-ntp.pool.ntp.org] Query failed: lookup 0.beevik-ntp.pool.ntp.org: no such host
--- FAIL: TestTime (0.02s)
=== RUN   TestTimeFailure
--- PASS: TestTimeFailure (5.01s)
=== RUN   TestQuery
    ntp_test.go:77: [0.beevik-ntp.pool.ntp.org] ----------------------
    ntp_test.go:78: [0.beevik-ntp.pool.ntp.org] NTP protocol version 4
    ntp_test.go:34: [0.beevik-ntp.pool.ntp.org] Query failed: lookup 0.beevik-ntp.pool.ntp.org: no such host
--- FAIL: TestQuery (0.00s)
=== RUN   TestValidate
--- PASS: TestValidate (0.00s)
=== RUN   TestBadServerPort
--- PASS: TestBadServerPort (0.00s)
=== RUN   TestTTL
--- PASS: TestTTL (0.00s)
=== RUN   TestQueryTimeout
--- PASS: TestQueryTimeout (0.00s)
=== RUN   TestShortConversion
--- PASS: TestShortConversion (0.00s)
=== RUN   TestLongConversion
--- PASS: TestLongConversion (0.00s)
=== RUN   TestOffsetCalculation
--- PASS: TestOffsetCalculation (0.00s)
=== RUN   TestOffsetCalculationNegative
--- PASS: TestOffsetCalculationNegative (0.00s)
=== RUN   TestMinError
--- PASS: TestMinError (0.01s)
=== RUN   TestTimeConversions
--- PASS: TestTimeConversions (0.00s)
=== RUN   TestKissCode
--- PASS: TestKissCode (0.00s)
FAIL
FAIL	github.com/beevik/ntp	5.091s
FAIL
```

This is caused by the package build host having no Internet access. Please change the test cases to not require Internet access. The positive side effect will be that the test cases can't break by changes to the NTP host 0.beevik-ntp.pool.ntp.org.

[1] Full log: https://launchpadlibrarian.net/575776629/buildlog_ubuntu-jammy-amd64.golang-github-beevik-ntp_0.3.0-2_BUILDING.txt.gz

**Comment by beevik** [comment]
I am unsure how to write a test that fails only when the runner has no internet access, as there is no simple way to detect if tests are failing simply because the client has no internet access.

**Comment by bdrung** [comment]
Can you provide an easy way to disable those tests and/or move them into a separate test file?

**Comment by beevik** [comment]
Can you please explain what is causing the ntp package tests to run in the first place?  It might help me address the problem if I understood better the environment in which my tests are being run.

**Comment by bdrung** [comment]
During package build `dh_auto_test -O--builddirectory=_build -O--buildsystem=golang` from debhelper is called which calls `go test -vet=off -v -p 4 github.com/beevik/ntp`. (see linked build log in the initial description). The Internet connection is blocked to avoid side effects. We can add options to the `go test` call.

**Comment by beevik** [comment]
I just committed v0.3.2 of the ntp package with a change that makes it possible to more easily filter out online unit tests.

All online test names are now prefixed by `TestOnline`.  To run only the offline tests, issue the following `go test` command:

```
go test -skip 'TestOnline.*'
```

**Comment by bdrung** [comment]
Thanks. That kind of skipping those test is exactly what I imagined.
