### ISSUE TITLE
Rename branch to `main`

### ISSUE THREAD

**Issue by abh** [beevik/ntp#40]
It'd be nice if the main branch was renamed to `main` instead of the legacy / old term.

(Also, thank you for this package -- the NTP Pool is using it to do hundreds of millions of monitoring probes every month!)

**Comment by beevik** [comment]
I agree.  I will research what steps need to be taken to migrate without disrupting users of the package.

**Comment by abh** [comment]
Unless a large number of users have active clones and are are sending PRs it's usually enough to just follow the GitHub instructions to rename the branch.

**Comment by beevik** [comment]
Looks like you're right.  As soon as I'm done with a PR in progress, I'll rename.  Thanks for maintaining the ntp pool!

**Comment by beevik** [comment]
Branch is now renamed to `main`.
