### ISSUE TITLE
1.2.0 broke querying IPv6 IPs

### ISSUE THREAD

**Issue by abh** [beevik/ntp#43]
In 1.2.0 the API for querying an IPv6 IP by IP address got a little awkward.

I used to just pass the IP (because that was the API, I think). In 1.2.0 I get a "missing port" address.

For an API that takes an optional IP usually sending the IP in brackets like `[fe80::1]` would work, but getTime() use net.JoinHostPort which messes that up a returns an error that `[[fe80::1]]` is missing a port number. (see https://go.dev/play/p/Wi0YDXQ0gUH )

Passing a string with the port number works `[fe80::1]:123`, but that seems to defeat the intention of having the Port number in the opts. Maybe the awkwardness comes from trying to support the port number in the address AND in the opts; currently making the opts version not actually work for IPv6 IPs.

Example of errors from SplitHostPort that might be helpful in figuring out how to fix it: https://go.dev/play/p/mJR_MD9PDUn

**Comment by beevik** [comment]
Oof.  Sorry about this.  Working on a fix.

**Comment by beevik** [comment]
Ok I just checked in a change that should fix this bug.  Before I issue a new release, would you mind verifying it for me?  I don't have IPv6 at home.

**Comment by beevik** [comment]
I spun up a VPS to test the IPv6 change, and it appears to work. Thanks for the report.

**Comment by abh** [comment]
Thanks @beevik! I didn't have time during the week to test; the fix looks good!

And the new features are great, too -- the KoD, ReferenceID, etc functions is stuff I did by hand before and code I look forward to removing. The features to support NTS are welcome, too! I really appreciate your work on this.
