### ISSUE TITLE
Expose NTP Server Version as a property

### ISSUE THREAD

**Issue by voltagex** [beevik/ntp#45]
I used your library to write a tiny diagnostic tool, thanks!

I noticed that Wireshark's dissector can tell me if the NTP version in the response was 3 or 4, it might be nice to have this in this library as well.

**Comment by beevik** [comment]
I just added a `Version` field to the `Response` struct.  See https://github.com/beevik/ntp/commit/bb6cad634aef4e211dfc518e4fc02ddeace7e84d

Thanks for the suggestion.
