### ISSUE TITLE
Check version of response

### ISSUE THREAD

**Issue by mbaklor** [beevik/ntp#46]
I have a need to filter server responses that are v3, since some of my devices only accept a v4 server, I'm halfway through checking the header flag myself in an extension, but was wondering if this might be a valid feature request? Would adding Version to the response struct make sense to anyone else?

**Comment by beevik** [comment]
This was added in a recent commit (3 months) ago: https://github.com/beevik/ntp/commit/bb6cad634aef4e211dfc518e4fc02ddeace7e84d

I have not created a release with this feature yet, since I was waiting for a few other features.  But I will go ahead and push out v1.4.0 if you need it.

**Comment by mbaklor** [comment]
😮 woah, didn't realize that was already in. Thanks!
